PINECONE_API_KEY = "pcsk_4TK7ee_2MQ2Y1oqcekKWwTytt9AMNEaJbKSLB487oEze4FvGkyq43MmTsLXgms7hvu9Hco"
PINECONE_ENVIRONMENT = "us-west1-gcp"
WEATHER_API_KEY = "d281e5d0bda91618efe65e3cd01aaefb"
NEWS_API_KEY = "cb2cd96a0f2e4ac2bfb3215865e71092"
